services:
  - type: web
    name: deepfake-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn registration.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
